spring:
  datasource:
    url: jdbc:h2:mem:testmanagercash
  application: 
    name: person-devh2 
  h2:
    console:
      enabled: true
      path: /h2
  
  jpa:
    show-sql: true

  config:
    activate:
      on-profile: devh2
server:
  port: 8081

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managercash
    username: root
    password: mysqltoor
  application:
    name: mc-devmysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    activate:
      on-profile: devmysql
server:
  port: 8080