spring:
  datasource:
    url: jdbc:h2:mem:testmanagercash
  application: 
    name: person-devh2 
  h2:
    console:
      enabled: true
      path: /h2
  
  jpa:
    show-sql: true

  config:
    activate:
      on-profile: devh2
server:
  port: 8081
  